/// TDesign默认主题
class CnDefaultTheme {
  static String defaultThemeConfig = '''
  {
    "default": {
        "ref":{
            "brandLightColor": "brandColor1",
            "brandFocusColor": "brandColor2",
            "brandDisabledColor": "brandColor3",
            "brandHoverColor": "brandColor6",
            "brandNormalColor": "brandColor7",
            "brandClickColor": "brandColor8",
            "errorLightColor": "errorColor1",
            "errorFocusColor": "errorColor2",
            "errorDisabledColor": "errorColor3",
            "errorHoverColor": "errorColor5",
            "errorNormalColor": "errorColor6",
            "errorClickColor": "errorColor7",
            "warningLightColor": "warningColor1",
            "warningFocusColor": "warningColor2",
            "warningDisabledColor": "warningColor3",
            "warningHoverColor": "warningColor4",
            "warningNormalColor": "warningColor5",
            "warningClickColor": "warningColor6",
            "successLightColor": "successColor1",
            "successFocusColor": "successColor2",
            "successDisabledColor": "successColor3",
            "successHoverColor": "successColor4",
            "successNormalColor": "successColor5",
            "successClickColor": "successColor6"
        },
        "color": {
            "brandColor1": "#F2F3FF",
            "brandColor2": "#D9E1FF",
            "brandColor3": "#B5C7FF",
            "brandColor4": "#8EABFF",
            "brandColor5": "#618DFF",
            "brandColor6": "#366EF4",
            "brandColor7": "#0052D9",
            "brandColor8": "#003CAB",
            "brandColor9": "#002A7C",
            "brandColor10": "#001A57",
            "errorColor1": "#FFF0ED",
            "errorColor2": "#FFD8D2",
            "errorColor3": "#FFB9B0",
            "errorColor4": "#FF9285",
            "errorColor5": "#F6685D",
            "errorColor6": "#D54941",
            "errorColor7": "#AD352F",
            "errorColor8": "#881F1C",
            "errorColor9": "#68070A",
            "errorColor10": "#490002",
            "warningColor1": "#FFF1E9",
            "warningColor2": "#FFD9C2",
            "warningColor3": "#FFB98C",
            "warningColor4": "#FA9550",
            "warningColor5": "#E37318",
            "warningColor6": "#BE5A00",
            "warningColor7": "#954500",
            "warningColor8": "#713300",
            "warningColor9": "#532300",
            "warningColor10": "#3B1700",
            "successColor1": "#E3F9E9",
            "successColor2": "#C6F3D7",
            "successColor3": "#92DAB2",
            "successColor4": "#56C08D",
            "successColor5": "#2BA471",
            "successColor6": "#008858",
            "successColor7": "#006C45",
            "successColor8": "#005334",
            "successColor9": "#003B23",
            "successColor10": "#002515",
            "grayColor1": "#F3F3F3",
            "grayColor2": "#EEEEEE",
            "grayColor3": "#E7E7E7",
            "grayColor4": "#DCDCDC",
            "grayColor5": "#C5C5C5",
            "grayColor6": "#A6A6A6",
            "grayColor7": "#8B8B8B",
            "grayColor8": "#777777",
            "grayColor9": "#5E5E5E",
            "grayColor10": "#4B4B4B",
            "grayColor11": "#383838",
            "grayColor12": "#2C2C2C",
            "grayColor13": "#242424",
            "grayColor14": "#181818"
        },
        "radius": {
            "radiusSmall": 3,
            "radiusDefault": 6,
            "radiusLarge": 9,
            "radiusExtraLarge": 12,
            "radiusRound": 9999,
            "radiusCircle": 9999
        }
    }
}

  ''';
}
